### PR TITLE
updated way to install packages

### PR DESCRIPTION
**Pull request by mpldr**
Changed the install packages to work with modules 

https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies

### CODE REVIEW

**Comment by andydotxyz** [comment]
This should not be necessary. Go get will install binaries if that is what your package specifies, and latest is the default version anyway.

**Comment by mpldr** [comment]
I've run into issues with plain `go get` quite some times recently and found that invoking `go install` instead would fix it.

**Comment by andydotxyz** [comment]
Unfortunately it breaks for earlier go versions and we currently support down to 1.12.
Perhaps you can share what sort of error messages you were seeing that led to this usage instead?
According to the docs on `go get`

> Executables will be installed in the directory named by the GOBIN environment variable

**Comment by mpldr** [comment]
That's understandable then. maybe replacing it with a hint could help prevent these issues... something along the lines:

>`go get` may fail in certain cases. In these cases you can try installing using `go install .......`

**Comment by andydotxyz** [comment]
> maybe replacing it with a hint could help prevent these issues...

I don't know, maybe. You've not shared what circumstances it failed in so it's hard to know.

**Comment by mpldr** [comment]
> 
> I don't know, maybe. You've not shared what circumstances it failed in so it's hard to know.

To be perfectly honest I have not bothered finding the root cause. Could have been a bug in go get for all I know. I only found this solution and went with it.

**Comment by andydotxyz** [comment]
I think without understanding what has happened we should not make this change as it goes against how some versions of Go work.
If you have more information we can re-open the ticket.

**Pull request closed without merging**
