### PR TITLE
Explore icons page

### LINKED ISSUE #18: Add a page for showing theme icons
I propose that we add a page for displaying the icons that exist within the theme package. A bit like how we do for layouts, but for icons instead. This would make it easy for users to see what icons exist and then pick the one that suits their use case.

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Fixes #18

* Uses Jekyll to iterate over icons
* Strips DTD
* inline includes icons within a figcaption
* Builds go:generate asset name (needs checking)
* uses unordered list with custom classes
* JS to alter body class list denoting light or dark theme
* CSS to display things as-is

<details>
<summary>Original Preview</summary>

Screenshot of WiP

</details>

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
Looks like some of the icons are using CSS styling for their colors. Fyne does fix this, but it might be a better idea to move those fill declarations into an attribute; so we can override using CSS.

**Comment by Lewiscowles1986** [comment]
I still think that having multiple headings with groups of icons would be a better move. From Fyne standpoint; changes would be needed into the repo to facilitate; or we could change approach on generating the icons on this page. In any case I quite like it.

**Comment by andydotxyz** [comment]
I think you've not committed all the files that you mention are needed (like the generator etc).
Also you should be aware that the light/dark preference can be changed by the browser dynamically...
If you put the CSS in our light/dark custom css files then the existing javascript will handle this for you.

**Comment by Lewiscowles1986** [comment]
Thanks Andy.

- I've not added the generator yet, but it's as I said in slack, currently just a cp command.
- The CSS & JS are isolated right now deliberately.
- I'm tweaking the CSS (natural grid effect doesn't look quite right to me)
- Working out a CSS fix for the icons that remain unaffected.

Really what I opened the draft for was commentary on the output. Will a grid of icons with just names work? Do we need something a little more robust? Are you happy with the HTML structure? Does the 300 seconds to generate represent a longer or shorter time to generate, and by how much?

**Comment by Lewiscowles1986** [comment]
```
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 224.242 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://0.0.0.0:4000//
  Server running... press ctrl-c to stop.
```

Because of the setup the `--watch` seems to not be respected.

**Comment by Lewiscowles1986** [comment]
### Updated Screenshots of progress 2021-12-31

Screenshot 2021-12-31 at 10-17-42 Theme Icons Develop using Fyne
Screenshot 2021-12-31 at 10-17-15 Theme Icons Develop using Fyne

**Comment by andydotxyz** [comment]
> Really what I opened the draft for was commentary on the output. Will a grid of icons with just names work?

:+1:  This works well - but the names should be API names, not file names

> 

> Does the 300 seconds to generate represent a longer or shorter time to generate, and by how much?

It previously took 30 seconds (maybe 35 since the API nagivation got more complex). Anything more than a minute is way too long.

**Comment by Lewiscowles1986** [comment]
This could just be that I am running Jekyll in a docker container maybe?

> done in 229.455 seconds.

It's fairly constant for me even on the master branch with no changes.

**Comment by Lewiscowles1986** [comment]
Screenshot 2022-01-01 at 17-50-35 Theme Icons Develop using Fyne
Screenshot 2022-01-01 at 17-50-49 Theme Icons Develop using Fyne

**Review by andydotxyz — CHANGES_REQUESTED** [review]
I don't think that we should inline *and* serve static assets, that is asking for confusion in the future.
To avoid this the markdown could be generated when you execute a script that currently copies assets...

**Comment by Lewiscowles1986** [comment]
How would it get content if this were the case? How to provide an edit link? Should it build an include?

**Comment by andydotxyz** [comment]
> How would it get content if this were the case? How to provide an edit link? Should it build an include?

I'm not sure exactly what the question is here sorry, did you check out how the layout script and page works?

**Comment by Lewiscowles1986** [comment]
Hello 👋,

Hope you are well. I Apologize for any confusion. Let me try to help us out. There were three questions. I'll try to pose them in a different way:

1. How would you propose the non-generated content be associated with the same page as the generated icon listing if using this script?
2. Your docs site has edit links on every page. So every page with that link should be editable. By making this a page that is generated. It will create a confusing loop for end-users to potentially PR and raise issues you know cannot land. Have you considered this?
3. If the icons are built at a different stage. Okay, so do you think building a file within include folder is an appropriate place to place the built icon list?
4. Bonus question: Before we go off on more changes. Are you now more-or-less happy with the icon names, presentation and the rest of the content? I feel like although this is *a solution* to an issue you've had open since a year; perhaps you have an internal direction, or as-yet uncommunicated wishes for this, which might be why it was not done prior.

👍 

Regarding understanding the system you made which is not Jekyll; I made some effort to understand it, but I probably don't have as deep knowledge of it as you do; and so felt much more comfortable skipping it.
Even the Jekyll setup was... Different to how I have seen Jekyll used before. If this is something else, please can we try to use other words to ask the question?

> did you check out how the layout script and page works?

**Comment by andydotxyz** [comment]
1. I still don't understand sorry. A generator script can write the file directly in, not sure what association means in this context
2. Apologies, that has been fixed - the generated pages don't have Edit links now
3. I'm not sure if we need an additional include for the icon listing. If it helps sure, but if it's one-off then just write the page instead of an include
4. Presentation looks good, not sure it needs the `()` though, as long as the name matches the API.

Thanks for getting this in. I don't have any pre-concieved notion of how it should work, other than fitting in with how the other pages look/work unless deviating is the right thing to do.

**Comment by Lewiscowles1986** [comment]
I think we are nearly there. hope you have had a nice weekend.

1. This page is not totally machine generated. It has two text sections at the top as well as the icons. Does that help with understanding the issue I see?
2. 👍 no need to apologize, it's one way to solve.
3. See 1
4. 👍 Will get those removed.

Cheers Andrew

**Comment by andydotxyz** [comment]
> 1. This page is not totally machine generated. It has two text sections at the top as well as the icons. Does that help with understanding the issue I see?

That helps thanks. Why not first pass by putting the content in the generator script and we could take it from there :).

Usually best to start from the smallest change and work from there. Improving / optimising could get a neater solution but it's easier to see how once the basics are in place.

**Comment by Jacalz** [comment]
Any news on this? It would be great to get his landed :)

**Comment by Lewiscowles1986** [comment]
I stopped, but the code is all there to generate etc, so feel free to pick it up. I'll close this for now. Sorry Andy

**Pull request closed without merging**
